// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5zDu8HlAHde_vIsunTtMF9aifoaPU9-Q',
    appId: '1:279881515402:web:7eb0a1e7565dc557ab8873',
    messagingSenderId: '279881515402',
    projectId: 'chatapp-f4307',
    authDomain: 'chatapp-f4307.firebaseapp.com',
    storageBucket: 'chatapp-f4307.appspot.com',
    measurementId: 'G-SERVD9KR3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc2J88a0F-Xs5I4HoBYMciCfb4U_9A5K4',
    appId: '1:279881515402:android:249107ca5c544fe2ab8873',
    messagingSenderId: '279881515402',
    projectId: 'chatapp-f4307',
    storageBucket: 'chatapp-f4307.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKhb_jT1EYvbo1fo_KiorCKil_ukmSx9I',
    appId: '1:279881515402:ios:71b2d7cb2d6b1e2dab8873',
    messagingSenderId: '279881515402',
    projectId: 'chatapp-f4307',
    storageBucket: 'chatapp-f4307.appspot.com',
    iosBundleId: 'com.chatapp.chatwx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKhb_jT1EYvbo1fo_KiorCKil_ukmSx9I',
    appId: '1:279881515402:ios:3ba613e17a4b17b0ab8873',
    messagingSenderId: '279881515402',
    projectId: 'chatapp-f4307',
    storageBucket: 'chatapp-f4307.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );
}
